name: auto

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: code repo Init
        run: |
          git config --global user.name "github action"
          git config --global user.email "github@action.com"

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update dir
        run: python update.py

      - name: Commit Changes
        run: |
          git add .
          git commit -m"action:`date +'%Y-%m-%d'`"
          git push origin github-page-docsify -f
